### ISSUE TITLE
Papertrail logger raises warnings with PHP7

### ISSUE THREAD

**Issue by andyt** [firegento/firegento-logger#122]
`Warning: A non-numeric value encountered in /var/www/htdocs/app/code/community/FireGento/Logger/Model/Papertrail/PapertrailSyslogMessage.php on line 59
`

https://github.com/firegento/firegento-logger/blob/develop/src/app/code/community/FireGento/Logger/Model/Papertrail/PapertrailSyslogMessage.php#L59

**Comment by furan917** [comment]
This is caused by 

/FireGento/Logger/Model/Papertrailsyslog.php::buildSysLogMessage returning 'error', 'warn', or 'debug' as a string. I simply manually edited PapertrailSyslogMessage.php::GetPriority to look as follows 

```
    private function GetPriority()
    {
        if (is_string($this->Severity)) {
            return $this->Severity;
        }

        return sprintf('<%d>', $this->Facility * 8 + $this->Severity);
    }
```

Its quick and dirty but it works. I just pull in our private edited copy from packagist to avoid any conflicts or overwrites.
